spring:
  application:
    name: courses
  #jpa:
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.MySQLDialect
        #format-sql: true
        #ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/courses
    username: root
    password: ${BD_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver